pipeline {
    agent {
        docker {
            image 'node:16-alpine'
            args '-u root' // Optional: sets user to root if needed
        }
    }
    
    stages {
        stage('Test') {
            steps {
                sh 'node --version'
            }
        }
    }
}
