pipeline {
    agent none
    
    stages {
        stage('Build') {
            agent {
                docker {
                    image 'node:16-alpine'
                    args '-u root' // Optional: sets user to root if needed
                }
            }
            steps {
                sh 'node --version'
            }
        }
    }
}
